- name: RHEL Python 3.9
  hosts: head_node
  become: true
  tasks:

  - name: Installing Python 3.9 and related packages
    ansible.builtin.yum:
      name:
        - python39
        - python39-devel
        - python39-pip
        - python39-requests
      state: latest
      update_cache: yes

  - name: Setting Python 3.9 as the default for python3
    community.general.alternatives:
      name: python3
      path: /usr/bin/python3.9

- name: Installing prerequisites for Hadoop on the Ubuntu cluster nodes.
  hosts: cluster_nodes
  become: true
  tasks:
    - name: Installing the deadsnakes PPA
      ansible.builtin.shell: add-apt-repository ppa:deadsnakes/ppa -y

    - name: Installing python3.9 on the Ubuntu cluster nodes.
      ansible.builtin.apt:
        name: python3.9
        state: present
        update_cache: yes

    - name: Verify python3.9 installation path
      ansible.builtin.shell: which python3.9
      register: python_path

    - name: Setting Python 3.9 as the default for python3
      ansible.builtin.command: update-alternatives --install /usr/bin/python3 python3 {{ python_path.stdout }} 1

    - name: Update alternatives to set Python 3.9 as default
      ansible.builtin.command: update-alternatives --config python3
      args:
        creates: /usr/bin/python3.9

    - name: Check the default Python version
      ansible.builtin.shell: python3 --version
      register: python_version

    - debug:
        var: python_version.stdout
